name: Build VT Proxy V2.1

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '20'

    - name: Install Yarn
      run: npm install -g yarn

    - name: Install dependencies
      run: yarn install

    - name: Build EXE
      run: yarn make

    - name: Upload Build Artifact
      uses: actions/upload-artifact@v4
      with:
        name: vtproxy-exe
        path: out/make/squirrel.windows/x64/*.exe
